<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>BetterGravityInstaller</AssemblyName>
    <RootNamespace>BetterGravityInstaller</RootNamespace>
    <Version>3.0.2</Version>
    <Product>BetterGravity Installer 3.0</Product>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*" />
    <EmbeddedResource Include="Patcher\**\*" />
    <None Update="Patcher\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
